version: 2
jobs:
  build:
    working_directory: ~/checkout
    docker:
      - image: openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps2-{{ .Branch }}

      - run:
          name: Update Cache
          command: ./gradlew resolveDependencies

      - save_cache:
          key: deps2-{{ .Branch }}
          paths:
            - "~/.gradle"

      - run:
          name: Validate Code
          command: ./gradlew check

      - run:
          name: Copy Artifacts
          command: |
           mkdir -p ~/test-results
           find . -maxdepth 5 -name 'TEST-*.xml' -exec cp {} ~/test-results/ \;

      - store_test_results:
          path: ~/test-results/

      - run:
          name: Upload Aritfacts
          command: |
            ./gradlew bintrayUpload
